name: flutter_start
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
#  sdk: '>=2.19.6 <3.0.0'
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.10.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  collection: ^1.17.0
  path: ^1.8.2

  # 包信息
  package_info_plus: ^3.1.0
  # 设备信息
  device_info_plus: ^8.2.0
  # 权限
  permission_handler: ^10.2.0
  # 存储路径
  path_provider: ^2.0.14
  # 振动
  vibration: ^1.7.7

  # GetX
  get: ^4.6.5

  # 屏幕适配
  flutter_screenutil: ^5.7.0

  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # toast
  fluttertoast: ^8.2.1
  # 弹窗
  easy_dialog: ^1.1.1
  # easyloading
  flutter_easyloading: ^3.0.5
  # popover
  popover: ^0.2.8+2
  # 诚城市选择
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 侧滑菜单
  flutter_slidable: ^3.0.0

  # http
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  # 缓存
  shared_preferences: ^2.0.5
  cached_network_image: ^3.2.3

  # 国际（多语言）
  intl: ^0.18.0

  # 摄像头拍摄
  camerawesome: ^1.4.0

  # 文件/图片选择
  file_picker: ^5.2.9
  image_picker: ^0.8.7+4
  wechat_assets_picker: ^8.5.0
  extended_image: ^8.0.1
  # 图片保存
  image_pickers: ^2.0.4+1
  # 生成二维码图片
  qr_flutter: ^4.1.0

  # uuid
  uuid: ^3.0.7
  # 日期选择
  flutter_datetime_picker_plus: ^2.0.1
  # 日期格式化
  day: ^0.8.0

  # 图片压缩
  flutter_image_compress: ^2.0.3
  # 视频压缩
  video_compress: ^3.1.2
  # 视频播放
  video_player: ^2.6.1
  chewie: ^1.5.0

  # 条形码、二维码识别
  mobile_scanner: ^3.2.0
  # web 打开 APP
  uni_links: ^0.5.1

  # 网络状态监控
  connectivity_plus: ^4.0.1
  # 打开指定资源（跳转App Store）
  url_launcher: ^6.1.10
  # 打开文件
  better_open_file: ^3.6.4

  # 加密安全 SHA
  crypto: ^3.0.2

  # webView
  webview_flutter: ^4.0.7
  webview_flutter_wkwebview: ^3.3.0
  webview_flutter_android: ^3.5.2

  # 分享
  share_plus: ^6.3.2

  # 高德地图
  amap_flutter_location: ^3.0.0
  amap_flutter_map: ^3.0.0
  amap_flutter_base: ^3.0.0

  # 动画
  animate_do: ^3.0.2
  flutter_speed_dial: ^6.2.0
  # 骨架屏
  skeletons: ^0.0.3

  # 错误、统计
  flutter_bugly: ^0.4.4

  # 调试、日志
  logger: ^1.3.0
  dio_log: ^2.0.4
  curl_logger_dio_interceptor: ^0.0.3

dependency_overrides:
  image: ^4.0.15
#  intl: ^0.18.0
#  win32: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # 自动生成 icons（flutter pub run flutter_launcher_icons）
  flutter_launcher_icons: ^0.11.0

  # 初始化页面视图（flutter pub run flutter_create_view）
  flutter_create_view:
    path: ./packages/create_view

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo-1024.png"

flutter_create_view:
  base_dir_release_path: "/lib/pages"
  template_dir_release_path: "_template"



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/images/guide/
    - assets/data/

  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf